name: Build Windows EXE
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build EXE
        run: pyinstaller --onefile --windowed gui.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist/" > .github/workflows/build.yml

